"""Auth endpoints for the mobile app.

``POST /api/auth/pair/claim`` is the only endpoint here today. It takes a
short pairing code (generated by the Settings page QR button) and
returns the API key + canonical base URL the mobile client should use.

The endpoint is intentionally NOT behind the API key gate — the whole
point of pairing is to obtain that key in the first place. Security
comes from:

  1. Pair codes are 8 chars of 31-char alphabet → 31^8 ≈ 8.5e11 space.
  2. Codes expire after 10 minutes.
  3. Codes are single-use (claimed → deleted).
  4. Only the logged-in desktop user can create a code (from Settings).
"""

from __future__ import annotations

from flask import Blueprint, jsonify, request

from ..errors import NotFound, ValidationError
from .. import pairing


bp = Blueprint("api_auth", __name__, url_prefix="/api/auth")


# The API key gate should not apply to this endpoint. We list it in
# ``auth._PUBLIC_PATHS`` via a path-prefix check below.
PAIR_CLAIM_PATH = "/api/auth/pair/claim"


@bp.route("/pair/claim", methods=["POST"])
def claim_pair():
    body = request.get_json(silent=True) or {}
    raw = (body.get("code") or "").strip().upper()
    # Users may type the pretty "ABCD-1234" form; normalise to ABCD1234.
    code = raw.replace("-", "").replace(" ", "")
    if not code:
        raise ValidationError("code is required")

    record = pairing.claim(code)
    if record is None:
        raise NotFound("pair code not found or expired")

    return jsonify({
        "api_key": record.api_key,
        "api_base": record.api_base,
    })
